### ISSUE TITLE
when i run test.py, a problem occured,and i didn't  change anything

### ISSUE THREAD

**Issue by zhangbaijin** [shepnerd/inpainting_gmcnn#15]
Traceback (most recent call last):
  File "/media/inpainting_gmcnn-master/pytorch/test.py", line 32, in <module>
    ourModel.load_networks(getLatest(os.path.join(config.load_model_dir, '*.pth')))
  File "/media/inpainting_gmcnn-master/pytorch/util/utils.py", line 84, in getLatest
    return files[sorted(range(len(file_times)), key=lambda x: file_times[x])[-1]]
IndexError: list index out of range

**Comment by shepnerd** [comment]
That list could be empty if no valid model path is fed. I guess you did not download the pretrained model and put that in checkpoints folder.
