### ISSUE TITLE
Trying to test and receiving error

### ISSUE THREAD

**Issue by muxgt** [shepnerd/inpainting_gmcnn#46]
Hi! I'm trying to test the pre-trained model on CelebA-HQ. I downloaded the checkpoint, put 1 image in the folder and provided a text file with its path. I type this: 
`python /content/inpainting_gmcnn/tensorflow/test.py --data_file /content/1.txt --load_model_dir '/content/drive/My Drive/Multicolumn' --random_mask 0` but receiving this error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1607, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 3 in both shapes must be equal, but are 32 and 64. Shapes are [7,7,5,32] and [7,7,5,64]. for 'Assign' (op: 'Assign') with input shapes: [7,7,5,32], [7,7,5,64].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/inpainting_gmcnn/tensorflow/test.py", line 45, in <module>
    vars_list))
  File "/content/inpainting_gmcnn/tensorflow/test.py", line 44, in <lambda>
    assign_ops = list(map(lambda x: tf.assign(x, tf.contrib.framework.load_variable(config.load_model_dir, x.name)),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/state_ops.py", line 227, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_state_ops.py", line 66, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1770, in __init__
    control_input_ops)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1610, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 3 in both shapes must be equal, but are 32 and 64. Shapes are [7,7,5,32] and [7,7,5,64]. for 'Assign' (op: 'Assign') with input shapes: [7,7,5,32], [7,7,5,64].

What may be the problem?

**Comment by shepnerd** [comment]
The given CelebA-HQ_512 model should be ran with the setting `--g_cnum 64` when you call `test.py`.

**Comment by muxgt** [comment]
Thanks, it's working. But for the model with stroke masks g_cnum needs to be 32. So is it different models that were pretrained?

**Comment by shepnerd** [comment]
For training on celeba-hq-512, we doubled the number of the used convolutional filters in every layer and inserted a few more layers for the performance.

**Comment by muxgt** [comment]
Actually on Celeba-HQ with stroke masks g_cnum is 32, not 64 like on square masks. So I don't really understand the logic.

**Comment by shepnerd** [comment]
Usually, filling rectangle missing regions is harder than filling the ones marked by strokes, thus we employ a model with the larger capacity than the usual for dealing with 512x512 face images.

**Comment by muxgt** [comment]
OK, thanks. I thought rectangle mask should be simpler since it's just fixed shape. I will try different options.
